### ISSUE TITLE
Getting error on image generation trigger

### ISSUE THREAD

**Issue by jatinkumarg** [victordibia/peacasso#2]
![image](https://user-images.githubusercontent.com/20503830/188470883-7841b097-d220-4d1a-95fc-b629cc46799b.png)

**Comment by victordibia** [comment]
Are you running this locally on your GPU enabled machine? 
For the web version I have (https://victordibia.com/peacasso/), there is currently no server attached (its expensive!) hence the error. 

Alternatively, you could run Peacasso for free in Colab using [this notebook ](https://colab.research.google.com/github/victordibia/peacasso/blob/master/notebooks/tutorial.ipynb)

-V
