### ISSUE TITLE
Is there somewhere I can change the default number of images to be generated from 6 to 1?

### ISSUE THREAD

**Issue by zeldatp151** [victordibia/peacasso#9]
The default always being 6 images just results in a lot of waisted time if I forget to change the settings. it would be nice to be able to change this default.

**Comment by victordibia** [comment]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/1547007/190874175-75ec55be-4163-4af1-98e7-7738f511e34c.png">

Yes. The `generation settings` popup menu lets you select the number of images and changes to this setting are persisted in localStorage on your browser (tested in Chrome). i.e, each time you change your settings and reload the UI, your previous settings should remain. Let me know your browser etc if it does not behave this way for you (possible bug). 

Btw .... I tend to set the number of steps to about 20 for faster generation also.
